version: '2.1'
services:
{{#microServices}}
  {{name}}:
    image: "{{dockerComposeImage}}"
    ports:
      - "{{port}}:{{port}}"
    {{#links}}
    {{#-first}}
    links:
    {{/-first}}
      - {{this}}
    {{/links}}
    {{#dependsOn}}
    {{#-first}}
    depends_on:
    {{/-first}}
      {{this}}:
        condition: service_healthy
    {{/dependsOn}}
    healthcheck:
      test: ["CMD", "curl", "-f", "{{dockerComposeHealthCheck}}"]
      interval: 5s
      retries: 20

{{/microServices}}
