{{#microServices}}
apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    run: {{name}}
spec:
  ports:
  - port: {{port}}
    protocol: TCP
  selector:
    run: {{name}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
spec:
  selector:
    matchLabels:
      run: {{name}}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{name}}
    spec:
      containers:
      - name: {{name}}
        image: "{{k8sDockerImage}}"
        ports:
        - containerPort: {{port}}
        livenessProbe:
          httpGet:
            path: {{k8sHealthCheck}}
            port: {{port}}
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

{{/microServices}}
