spring:
  mustache:
    expose-request-attributes: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${SPRING_GITHUB_CLIENT_ID}
            client-secret: ${SPRING_GITHUB_CLIENT_SECRET}
            scope: user, public_repo

playground:
  env:
    boms:
      azure-dependencies-bom:
        groupId: com.microsoft.azure
        artifactId: azure-dependencies-bom
        versionProperty: azure-dependencies-bom.version
        mappings:
          - versionRange: "1.0.0.M2"
            version: 1.0.0.M2
      spring-cloud-azure:
        groupId: com.microsoft.azure
        artifactId: spring-cloud-azure-dependencies
        versionProperty: spring-cloud-azure.version
        mappings:
          - versionRange: "2.0.0.RELEASE"
            version: 1.0.0.M2
      azure-spring-boot:
        groupId: com.microsoft.azure
        artifactId: azure-spring-boot-bom
        versionProperty: azure-spring-boot.version
        mappings:
          - versionRange: "2.0.0.RELEASE"
            version: 2.0.5
      spring-cloud:
        groupId: org.springframework.cloud
        artifactId: spring-cloud-dependencies
        versionProperty: spring-cloud.version
        order: 50
        mappings:
          - versionRange: "[1.2.3.RELEASE,1.3.0.RELEASE)"
            version: Angel.SR6
          - versionRange: "[1.3.0.RELEASE,1.4.0.RELEASE)"
            version: Brixton.SR7
          - versionRange: "[1.4.0.RELEASE,1.4.x.RELEASE]"
            version: Camden.SR7
          - versionRange: "[1.5.0.RELEASE,1.5.x.RELEASE]"
            version: Edgware.SR3
          - versionRange: "[1.5.x.BUILD-SNAPSHOT,2.0.0.M1)"
            version: Edgware.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
          - versionRange: "[2.0.0.M3, 2.0.0.M5)"
            version: Finchley.M2
            repositories: spring-milestones
          - versionRange: "[2.0.0.M5, 2.0.0.M5]"
            version: Finchley.M3
            repositories: spring-milestones
          - versionRange: "[2.0.0.M6, 2.0.0.M6]"
            version: Finchley.M4
            repositories: spring-milestones
          - versionRange: "[2.0.0.M7, 2.0.0.M7]"
            version: Finchley.M5
            repositories: spring-milestones
          - versionRange: "[2.0.0.RC1, 2.0.0.RC1]"
            version: Finchley.M6
            repositories: spring-milestones
          - versionRange: "[2.0.0.RC2,2.0.0.RC2]"
            version: Finchley.M7
            repositories: spring-milestones
          - versionRange: "[2.0.0.RELEASE,2.0.2.RELEASE]"
            version: Finchley.M9
            repositories: spring-milestones
          - versionRange: "[2.0.3.RELEASE,2.0.3.RELEASE]"
            version: Finchley.RELEASE
            repositories: spring-milestones
          - versionRange: "2.0.x.BUILD-SNAPSHOT"
            version: Finchley.BUILD-SNAPSHOT
            repositories: spring-snapshots,spring-milestones
  dependencies:
    - name: Web
      content:
        - name: Web
          id: web
          description: Full-stack web development with Tomcat and Spring MVC
          weight: 100
          facets:
            - web
            - json
          links:
            - rel: guide
              href: https://spring.io/guides/gs/rest-service/
              description: Building a RESTful Web Service
            - rel: reference
              href: http://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-developing-web-applications
            - rel: guide
              href: https://spring.io/guides/gs/serving-web-content/
              description: Serving Web Content with Spring MVC
            - rel: guide
              href: https://spring.io/guides/tutorials/bookmarks/
              description: Building REST services with Spring
    - name: Jpa
      content:
        - name: Jpa
          id: jpa
          description: Spring data Jpa
          groupId: org.springframework.boot
          artifactId: spring-boot-starter-data-jpa
          weight: 100
    - name: Spring Thymeleaf
      content:
        - name: Spring Thymeleaf
          id: spring-thymeleaf
          description: Spring Thymeleaf
          groupId: org.springframework.boot
          artifactId: spring-boot-starter-thymeleaf
    - name: Thymeleaf Spring Security
      content:
        - name: Thymeleaf Spring Security
          id: thymeleaf-extra
          description: Spring Thymeleaf
          groupId: org.thymeleaf.extras
          artifactId: thymeleaf-extras-springsecurity4
    - name: Spring Security Oauth2 Client
      content:
        - name: Spring Security Oauth2 Client
          id: spring-security-oauth2-client
          description: Spring Security
          groupId: org.springframework.security
          artifactId: spring-security-oauth2-client
    - name: Spring Security Oauth2 Jose
      content:
        - name: Spring Security Oauth2 Jose
          id: spring-security-oauth2-jose
          description: Spring Security
          groupId: org.springframework.security
          artifactId: spring-security-oauth2-jose
    - name: Spring Security
      content:
        - name: Spring Security
          id: spring-security
          description: Spring Security
          groupId: org.springframework.boot
          artifactId: spring-boot-starter-security
    - name: Azure Cosmosdb
      content:
        - name: Azure Cosmosdb Spring Boot Starter
          id: azure-cosmosdb
          description: Cosmosdb Spring Boot Starter
          groupId: com.microsoft.azure
          artifactId: azure-documentdb-spring-boot-starter
          weight: 100
        - name: Spring Date Cosmosdb
          id: spring-data-cosmosdb
          description: Cosmosdb Spring Boot Starter
          groupId: com.microsoft.azure
          artifactId: spring-data-cosmosdb
          versionRange: 2.0.4
          weight: 100
    - name: Azure Key Vault
      content:
      - name: Azure Key Vault Secrets Spring Boot Starter
        id: azure-keyvault-secrets
        description: Key Vault Secrets Spring Boot Starter
        groupId: com.microsoft.azure
        artifactId: azure-keyvault-secrets-spring-boot-starter
        weight: 100
    - name: Cloud Config
      bom: spring-cloud
      versionRange: 1.2.3.RELEASE
      content:
        - name: Config Client
          id: cloud-config-client
          description: spring-cloud-config Client
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-config
          weight: 100
        - name: Config Server
          id: cloud-config-server
          description: Central management for configuration via a git or svn backend
          groupId: org.springframework.cloud
          artifactId: spring-cloud-config-server
          links:
            - rel: guide
              href: https://spring.io/guides/gs/centralized-configuration/
              description: Centralized Configuration
        - name: Vault Configuration
          id: cloud-starter-vault-config
          description: Configuration management with HashiCorp Vault
          versionRange: 1.5.3.RELEASE
          starter: false
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-vault-config
    - name: Cloud Discovery
      bom: spring-cloud
      versionRange: 1.2.3.RELEASE
      content:
        - name: Eureka Discovery
          id: cloud-eureka-client
          description: Service discovery using spring-cloud-netflix and Eureka
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-netflix-eureka-client
          weight: 100
          mappings:
            - versionRange: "[1.2.3.RELEASE,1.5.x.RELEASE]"
              artifactId: spring-cloud-starter-eureka
            - versionRange: "1.5.0.BUILD-SNAPSHOT"
        - name: Eureka Server
          id: cloud-eureka-server
          description: spring-cloud-netflix Eureka Server
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-netflix-eureka-server
          links:
            - rel: guide
              href: https://spring.io/guides/gs/service-registration-and-discovery/
              description: Service Registration and Discovery
          mappings:
            - versionRange: "[1.2.3.RELEASE,1.5.x.RELEASE]"
              artifactId: spring-cloud-starter-eureka-server
            - versionRange: "1.5.0.BUILD-SNAPSHOT"
    - name: Cloud Routing
      bom: spring-cloud
      versionRange: 1.2.3.RELEASE
      content:
        - name: Gateway
          id: cloud-gateway
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-gateway
          description: Intelligent and programmable routing with the reactive Spring Cloud Gateway
          versionRange: 2.0.0.M5
          links:
            - rel: guide
              href: https://github.com/spring-cloud-samples/spring-cloud-gateway-sample
              description: Using Spring Cloud Gateway
    - name: Cloud Circuit Breaker
      bom: spring-cloud
      versionRange: 1.2.3.RELEASE
      content:
        - name: Hystrix
          id: cloud-hystrix
          description: Circuit breaker with spring-cloud-netflix Hystrix
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-netflix-hystrix
          links:
            - rel: guide
              href: https://spring.io/guides/gs/circuit-breaker/
              description: Circuit Breaker
          mappings:
            - versionRange: "[1.2.3.RELEASE,1.5.x.RELEASE]"
              artifactId: spring-cloud-starter-hystrix
            - versionRange: "1.5.0.BUILD-SNAPSHOT"
        - name: Hystrix Dashboard
          id: cloud-hystrix-dashboard
          description: Circuit breaker dashboard with spring-cloud-netflix Hystrix
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-netflix-hystrix-dashboard
          mappings:
            - versionRange: "[1.2.3.RELEASE,1.5.x.RELEASE]"
              artifactId: spring-cloud-starter-hystrix-dashboard
            - versionRange: "1.5.0.BUILD-SNAPSHOT"
    - name: Spring Cloud Azure
      bom: spring-cloud-azure
      versionRange: "1.5.4.RELEASE"
      content:
        - name: Azure Redis Cache
          id: azure-redis-cache
          groupId: com.microsoft.azure
          artifactId: spring-azure-starter-cache
          description: Azure Redis Cache Integration
          links:
            - rel: sample
              href: https://github.com/Microsoft/spring-cloud-azure/tree/release/1.0.0.M2/spring-cloud-azure-samples/spring-cloud-azure-cache-sample
              description: Spring Azure redis cache sample
            - rel: reference
              href: https://github.com/Microsoft/spring-cloud-azure/tree/release/1.0.0.M2/spring-cloud-azure-starters/spring-azure-starter-cache
              description: Reference doc
        - name: Azure Storage
          id: azure-storage
          groupId: com.microsoft.azure
          artifactId: spring-azure-starter-storage
          description: Azure Storage Integration
          links:
            - rel: sample
              href: https://github.com/Microsoft/spring-cloud-azure/tree/release/1.0.0.M2/spring-cloud-azure-samples/spring-cloud-azure-storage-sample
              description: Spring Azure storage sample
            - rel: reference
              href: https://github.com/Microsoft/spring-cloud-azure/tree/release/1.0.0.M2/spring-cloud-azure-starters/spring-azure-starter-storage
              description: Reference doc
        - name: Azure Event Hub Stream Binder
          id: azure-eventhub-binder
          groupId: com.microsoft.azure
          artifactId: spring-cloud-azure-eventhub-stream-binder
          description: Spring Cloud Stream Event Hub Binder
          links:
            - rel: sample
              href: https://github.com/Microsoft/spring-cloud-azure/tree/release/1.0.0.M2/spring-cloud-azure-samples/spring-cloud-azure-eventhub-binder-sample
              description: Spring Cloud Stream with Event Hub Binder sample
            - rel: reference
              href: https://github.com/Microsoft/spring-cloud-azure/tree/release/1.0.0.M2/spring-cloud-azure-eventhub-stream-binder
              description: Reference doc
        - name: Azure Event Hub
          id: azure-eventhub-starter
          groupId: com.microsoft.azure
          artifactId: spring-cloud-azure-starter-eventhub
          description: Azure Event Hub Integration
          links:
            - rel: sample
              href: https://github.com/Microsoft/spring-cloud-azure/tree/release/1.0.0.M2/spring-cloud-azure-samples/spring-cloud-azure-eventhub-binder-sample
              description: Spring Cloud Stream with Event Hub Binder sample
            - rel: reference
              href: https://github.com/Microsoft/spring-cloud-azure/tree/release/1.0.0.M2/spring-cloud-azure-starters/spring-cloud-azure-starter-eventhub
              description: Reference doc
    - name: Azure Spring Boot
      bom: azure-spring-boot
      versionRange: "2.0.0.RELEASE"
      content:
        - name: Azure Active Directory
          id: azure-active-directory
          groupId: com.microsoft.azure
          artifactId: azure-active-directory-spring-boot-starter
          description: Azure Active Directory
          links:
            - rel: sample
              href: https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-backend-sample
              description: Spring Security 5 with Azure Active Directory sample
            - rel: reference
              href: https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot-starters/azure-active-directory-spring-boot-starter/README.md
              description: Reference doc
  services:
    - name: Infrastructure Spring Cloud Modules
      content:
        - name: Spring Cloud Config Server
          id: cloud-config-server
          defaultPort: 8888
          description: Central place to manage external properties for applications across all environments
          mandatory: true
        - name: Spring Cloud Gateway
          id: cloud-gateway
          defaultPort: 9999
          description: API Gateway to route for APIs
          mandatory: true
        - name: Spring Cloud Eureka Server
          id: cloud-eureka-server
          defaultPort: 8761
          description: Spring Cloud Service Registry and Discovery
          mandatory: true
        - name: Spring Cloud Hystrix Dashboard
          id: cloud-hystrix-dashboard
          defaultPort: 7979
          description: Circuit breaker dashboard with spring-cloud-netflix Hystrix
          mandatory: false
    - name: Azure Spring Cloud Modules
      content:
        - name: Azure Event Hub
          id: azure-eventhub-binder
          description: Spring Cloud Stream Binder for Azure Event Hub
        - name: Azure Redis Cache
          id: azure-redis-cache
          description: Spring Caching with Azure Redis Cache
        - name: Azure Storage
          id: azure-storage
          description: Spring Cloud Resource with Azure Storage
        - name: Azure Active Directory
          id: azure-active-directory
          description: Spring Security with Azure Active Directory
        - name: Azure Cosmos DB
          id: azure-cosmosdb
          description: Spring Data Azure Cosmos DB (SQL API)
        - name: Azure Key Vault
          id: azure-keyvault-secrets
          description: Spring Boot with Azure Key Vault
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      sts-id: microservice.zip
      tags:
        build: maven
        format: project
      default: true
      action: /microservice.zip
    - name: Maven POM
      id: maven-build
      description: Generate a Maven pom.xml
      sts-id: pom.xml
      tags:
        build: maven
        format: build
      default: false
      action: /pom.xml
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  javaVersions:
    - id: 10
      default: false
    - id: 9
      default: false
    - id: 1.8
      name: 8
      default: true
    - id: 1.7
      name: 7
      default: false
  languages:
    - name: Java
      id: java
      default: true
  bootVersions:
    - name : Latest SNAPSHOT
      id: 1.2.4.BUILD-SNAPSHOT
      default: false
    - name: 1.2.3
      id: 1.2.3.RELEASE
      default: true
    - name: 1.1.12
      id: 1.1.12.RELEASE
      default: false
server:
  use-forward-headers: true
