server:
  port: {{port}}

spring:
  cloud:
    gateway:
      routes:
      {{#azureServices}}
      - id: {{name}}
        uri: lb://{{name}}
        predicates:
        - Path=/{{name}}/**
      {{/azureServices}}